package com.noticeboardapp.utils_classes;

import com.gauravtak.scheduler_assignment.NoticeBoardApp;
import com.noticeboardapp.db_storage.DatabaseHandler;
import com.noticeboardapp.model_classes.NoticeDataBean;

public class DummyDataClasses {
    public static void addDummyNotices()
    {

        NoticeDataBean noticeDataBean = new NoticeDataBean(1,"Sports Week","Sports Division","Sports days (British English) or field days (American English) are events staged by many schools and offices in which people participate in competitive sporting activities, often with the aim of winning trophies or prizes. Though they are often held at the beginning of summer, they are staged in the autumn or spring seasons, especially in countries where the summer is very harsh. Schools stage many sports days in which children participate in the sporting events. It is usually held in elementary schools.\n" +
                "\n" +
                "In schools which use a house system a feature of the school is the competition between the houses; this is especially brought out during sporting events such as an inter-house sports day.\n" +
                "\n" +
                "Games that are played on school sports days can be wide and varied. They can include straightforward sprints and longer races for all age groups as well as egg and spoon races. Three legged races are run as well as sack races, wheelbarrow races, and parent and child races","https://image.shutterstock.com/image-photo/grand-sports-collage-soccer-basketball-260nw-1071589835.jpg","Mr. Vivek Sharma","vivek@gmail.com","15-19 Aug 2020","https://en.wikipedia.org/wiki/Sport","Sports");
        new DatabaseHandler(NoticeBoardApp.Companion.getMContext()).addNotice(noticeDataBean);

        NoticeDataBean noticeDataBean1 = new NoticeDataBean(2,"Music Week","Music Division","Music is an art form, and cultural activity, whose medium is sound. General definitions of music include common elements such as pitch (which governs melody and harmony), rhythm (and its associated concepts tempo, meter, and articulation), dynamics (loudness and softness), and the sonic qualities of timbre and texture (which are sometimes termed the \"color\" of a musical sound). Different styles or types of music may emphasize, de-emphasize or omit some of these elements. Music is performed with a vast range of instruments and vocal techniques ranging from singing to rapping; there are solely instrumental pieces, solely vocal pieces (such as songs without instrumental accompaniment) and pieces that combine singing and instruments. The word derives from Greek μουσική (mousike; \"art of the Muses\").[1] See glossary of musical terminology.","https://www.online-tech-tips.com/wp-content/uploads/2019/05/music.png","Mr. Anjali Gupta","anjali@gmail.com","10-15 Sept 2020","https://en.wikipedia.org/wiki/Music","Music");
        new DatabaseHandler(NoticeBoardApp.Companion.getMContext()).addNotice(noticeDataBean1);

        NoticeDataBean noticeDataBean2 = new NoticeDataBean(3,"Exam Week","Exam Division","A test or examination (informally, exam or evaluation) is an assessment intended to measure a test-taker's knowledge, skill, aptitude, physical fitness, or classification in many other topics (e.g., beliefs).[1] A test may be administered verbally, on paper, on a computer, or in a predetermined area that requires a test taker to demonstrate or perform a set of skills. Tests vary in style, rigor and requirements. For example, in a closed book test, a test taker is usually required to rely upon memory to respond to specific items whereas in an open book test, a test taker may use one or more supplementary tools such as a reference book or calculator when responding. A test may be administered formally or informally. An example of an informal test is a reading test administered by a parent to a child. A formal test might be a final examination administered by a teacher in a classroom or an I.Q. test administered by a psychologist in a clinic. Formal testing often results in a grade or a test score.[2] A test score may be interpreted with regards to a norm or criterion, or occasionally both. The norm may be established independently, or by statistical analysis of a large number of participants. An exam is meant to test a persons knowledge or willingness to give time to manipulate that subject.","https://ichef.bbci.co.uk/news/410/cpsprodpb/1839E/production/_111203299_gettyimages-1146240359.jpg","Mr. Vikas Roy","vikas@gmail.com","10-15 July 2020","https://en.wikipedia.org/wiki/Test_(assessment)","Examination");
        new DatabaseHandler(NoticeBoardApp.Companion.getMContext()).addNotice(noticeDataBean2);
        NoticeDataBean noticeDataBean3 = new NoticeDataBean(4,"Online Study Material","Academics Division","The Buddha sat under the bodhi tree for 49 days until his spiritual awakening that spawned one of the world's great religions, Buddhism. So as we patiently for our lives to return to normal, now is the perfect opportunity to explore existence through one of the central practices of Buddhism -- meditation. Essentially, meditation is the art of paying attention to a sense of awareness. This is done by focusing on a particular object, thought, or activity, such as breathing. With regular practice, some people report an intense spiritual experience, namely a sense of overwhelming peace along with a feeling of connectedness to a higher, eternal sense of being beyond our usual conception of the self. In fact, this idea is central to Buddhist philosophy. \n" +
                "\n" +
                "But this kind of thinking isn't for everyone. And when it comes to meditation, it doesn't need to be. It's just as beneficial as a secular practice as it is as a spiritual one. Studies have shown that regular meditation can reduce stress and anxiety, boost IQ, and develop a whole range of positive emotions, including empathy and compassion. Moreover, regular meditators show extra activity in the pre-frontal cortex, the part of the brain that does our 'rational' thinking. As such, meditation can improve impulse control, emotional stability, and your sense of self-awareness.\n" +
                "\n" +
                "But the most exciting research focuses on neuroplasticity. Work by a group of scientists from Harvard found that meditation rewires parts of the brain for improved function. This helps people think more creatively, maintains cognitive function into old age, and can even rewire negative neural pathways formed by years of abuse or early traumatic experiences.","https://live.mrf.io/statics/i/ps/storage.googleapis.com/thisday-846548948316-wp-data/wp-media/2020/05/6e234a9c-online-learning.jpg?width=1200&enable=upscale","Mr. Nikhil Sharma","nikhilsharma@gmail.com","10-15 July 2020","https://www.onlinestudies.com/Courses/","Examination");
        new DatabaseHandler(NoticeBoardApp.Companion.getMContext()).addNotice(noticeDataBean3);
    }
}
